description: "Workflows made by Typpi / Nick2bad4u"
plugins:
    - "jekyll-sitemap"
    - "jekyll-seo-tag"
    - "jekyll-paginate"
    - "jekyll-feed"
    - "jekyll-archives"
    - "jekyll-language-plugin"
    - "jekyll-algolia"
    - "jekyll-mentions"
    - "jekyll-admin"
    - "jekyll-loading-lazy"
remote_theme: "pages-themes/hacker@v0.2.0"
title: "Workflow Templates"
url: "https://nick2bad4u.github.io/workflow-templates" # the base hostname & protocol for your site
