name: "Dependabot Auto-Merge"

on:
    pull_request:
        branches:
            - "main"
            - "master"
            - "develop"
            - "release/*"
        types:
            - "opened"
            - "synchronize"
            - "reopened"
            - "ready_for_review"
    merge_group:
        branches:
            - "main"
            - "master"
            - "develop"
            - "release/*"
        types:
            - "checks_requested"

permissions: {}

jobs:
    dependabot-auto-merge:
        permissions:
            contents: "write"
            pull-requests: "write"
        uses: "Nick2bad4u/workflow-templates/.github/workflows/reusable-auto-merge-dependabot.yml@aca93c9f0f022b2c006bde8102bdb1588878b713"
        with:
            semver-policy: "patch,minor,major"
