name: "Deploy Docusaurus"

on:
    push:
        branches:
            - "main"
            - "master"
        paths:
            - "docs/**"
            - "docusaurus.config.js"
            - "package.json"
            - "package-lock.json"
    workflow_dispatch:

permissions: {}

jobs:
    deploy:
        permissions:
            contents: "read"
            pages: "write"
            id-token: "write"
        uses: "Nick2bad4u/workflow-templates/.github/workflows/reusable-docusaurus-deploy.yml@main"
