# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: "Deploy Jekyll To GitHub Pages"

run-name: "${{ github.workflow }} (${{ github.ref_name || github.run_id }})"

on:
    push:
        branches:
            - "main"
            - "master"
    workflow_dispatch:

concurrency:
    group: "jekyll-pages-deploy-${{ github.workflow }}-${{ github.ref || github.run_id }}"
    cancel-in-progress: true

permissions: {}

jobs:
    jekyll-pages-deploy:
        name: "Deploy Jekyll To GitHub Pages"
        permissions:
            contents: "read"
            id-token: "write"
            pages: "write"
        uses: "Nick2bad4u/workflow-templates/.github/workflows/reusable-jekyll-pages-deploy.yml@main"
