# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: "Microsoft Security DevOps"

run-name: "${{ github.workflow }} (${{ github.ref_name || github.run_id }})"

on:
    schedule:
        - cron: "23 9 * * *"
    push:
        branches:
            - "main"
            - "master"
    pull_request:
        branches:
            - "main"
            - "master"
    merge_group:
        branches:
            - "main"
            - "master"
        types:
            - "checks_requested"
    workflow_dispatch:

concurrency:
    group: "microsoft-security-devops-${{ github.workflow }}-${{ github.ref || github.run_id }}"
    cancel-in-progress: true

permissions: {}

jobs:
    microsoft-security-devops:
        name: "Microsoft Security DevOps"
        permissions:
            actions: "read"
            contents: "read"
            security-events: "write"
        uses: "Nick2bad4u/workflow-templates/.github/workflows/reusable-microsoft-security-devops.yml@main"
