# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: "Typos Spell Check"

run-name: "${{ github.workflow }} (${{ github.ref_name || github.run_id }})"

on:
    push:
        branches:
            - "main"
            - "master"
    pull_request:
        branches:
            - "main"
            - "master"
    merge_group:
        branches:
            - "main"
            - "master"
        types:
            - "checks_requested"
    workflow_dispatch:

concurrency:
    group: "typos-spellcheck-${{ github.workflow }}-${{ github.ref || github.run_id }}"
    cancel-in-progress: true

permissions: {}

jobs:
    typos-spellcheck:
        name: "Typos Spell Check"
        permissions:
            contents: "read"
        uses: "Nick2bad4u/workflow-templates/.github/workflows/reusable-typos-spellcheck.yml@main"
