# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: "Actionlint"

on:
    workflow_call:

permissions:
    contents: "read"
    pull-requests: "write"

jobs:
    actionlint:
        name: "Run Actionlint"
        runs-on: "ubuntu-latest"
        timeout-minutes: 15
        steps:
            - name: "Harden runner"
              uses: "step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920" # v2.20.0
              with:
                  egress-policy: "audit"

            - name: "Checkout"
              uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1

            - name: "Actionlint"
              uses: "devops-actions/actionlint@9fb9c192862f19e684586ca84b500461bcd8a541" # v0.1.12
