# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: "Actionlint"

on:
    workflow_call:

permissions:
    contents: "read"
    pull-requests: "write"

jobs:
    actionlint:
        name: "Run Actionlint"
        runs-on: "ubuntu-latest"
        timeout-minutes: 15
        steps:
            - name: "Harden runner"
              uses: "step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c" # v2.21.0
              with:
                  egress-policy: "audit"

            - name: "Checkout"
              uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1

            - name: "Actionlint"
              uses: "devops-actions/actionlint@ec02b36684b2f574f1d219ad0a43b082e46bf3e4" # v0.1.13
