# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: "Typos Spell Check"

on:
    workflow_call:

permissions:
    contents: "read"

jobs:
    typos:
        name: "Typos Spell Check"
        runs-on: "ubuntu-latest"
        timeout-minutes: 20
        steps:
            - name: "Harden runner"
              uses: "step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1" # v2.21.1
              with:
                  egress-policy: "audit"

            - name: "Checkout"
              uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1

            - name: "Run typos"
              uses: "crate-ci/typos@00f422f3b19c57bc6338715ebfe3316d38768461" # v1.50.3
              with:
                  files: "."
