name: Label Pull Requests

on:
    workflow_call:
concurrency:
    group: labeler-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read
    pull-requests: write

jobs:
    labeler:
        name: Label Pull Requests
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Harden runner
              uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
              with:
                  egress-policy: audit

            - name: Apply labels
              uses: actions/labeler@7c0734f987ad0bb30ee8da210773b800ee2016d3 # v6.0.1
              with:
                  configuration-path: .github/labeler.yml
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  sync-labels: true
